log syslog all;
router id 104.244.76.122;

protocol static static_bgp {
  ipv6;
  route 2a05:dfc1:3800::00/48 via 2605:6400:30:f9a2::2;
  route 2a05:dfc1:3838::00/48 via 2605:6400:30:f9a2::2;
}

protocol device {
  scan time 5;
}

protocol direct {
  interface "dummy*";
  ipv6 {
    import all;
  };
}

protocol kernel {
  ipv6 {
    export all;
  };
  scan time 15;
}

protocol bgp frantech {
  local as 198714;
  source address 2605:6400:30:f9a2::2;
  neighbor 2605:6400:ffff::2 as 53667;
  password "2o40FtHH";
  multihop 2;
  ipv6 {
    import none;
    export where proto = "static_bgp";
  };
  graceful restart on;
}
